#!/bin/bash
#SBATCH -N 1      # nodes requested
#SBATCH --job-name=barbellspeclearn
#SBATCH --output=barbell.out
#SBATCH --error=barbell.err
#SBATCH --mem=36000
#SBATCH --qos=medium
#SBATCH --gres=gpu:1
srun -n 1 -c 1 --exclusive /slurm-storage/jacbam/.conda/envs/bdl/bin/python -m newsynth.run_multiple --yaml_name barbell-specbunn_learn &
srun -n 1 -c 1 --exclusive /slurm-storage/jacbam/.conda/envs/bdl/bin/python -m newsynth.run_multiple --yaml_name barbell-gcn &
